name: run meteoAtual.py

on:
  schedule:
    - cron: '0 */0,5 * * *'  # hourly 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup
          pip install requests
          
      - name: execute py script # run main.py
        run: python meteoAtual.py