name: run meteoAtual.py  

on:
  schedule:
    - cron: '*/30 * * * *'  # every 30 minutes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2.3.4 # Checkout the repository content to github runner.

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install python version 
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4
          pip install requests
          pip install lxml
          
      - name: execute py script # run main.py
        run: python meteoAtual.py